# Automatically generated by configure
PREFIX=/mingw
libdir=/mingw/lib
incdir=/mingw/include
AR=i586-mingw32msvc-ar
CC=i586-mingw32msvc-gcc
RANLIB=i586-mingw32msvc-ranlib
STRIP=i586-mingw32msvc-strip
BUILD_SHARED=yes
BUILD_STATIC=yes
BUILD_MSVC=no
LIBCMD=echo ignoring lib
